/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IkeaRouteImport } from './routes/ikea'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SolicitudTokenRouteImport } from './routes/solicitud.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IkeaRoute = IkeaRouteImport.update({
  id: '/ikea',
  path: '/ikea',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SolicitudTokenRoute = SolicitudTokenRouteImport.update({
  id: '/solicitud/$token',
  path: '/solicitud/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ikea': typeof IkeaRoute
  '/precios': typeof PreciosRoute
  '/reservar': typeof ReservarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/solicitud/$token': typeof SolicitudTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ikea': typeof IkeaRoute
  '/precios': typeof PreciosRoute
  '/reservar': typeof ReservarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/solicitud/$token': typeof SolicitudTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ikea': typeof IkeaRoute
  '/precios': typeof PreciosRoute
  '/reservar': typeof ReservarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/solicitud/$token': typeof SolicitudTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ikea'
    | '/precios'
    | '/reservar'
    | '/reset-password'
    | '/servicios'
    | '/admin'
    | '/solicitud/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ikea'
    | '/precios'
    | '/reservar'
    | '/reset-password'
    | '/servicios'
    | '/admin'
    | '/solicitud/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ikea'
    | '/precios'
    | '/reservar'
    | '/reset-password'
    | '/servicios'
    | '/_authenticated/admin'
    | '/solicitud/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IkeaRoute: typeof IkeaRoute
  PreciosRoute: typeof PreciosRoute
  ReservarRoute: typeof ReservarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiciosRoute: typeof ServiciosRoute
  SolicitudTokenRoute: typeof SolicitudTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ikea': {
      id: '/ikea'
      path: '/ikea'
      fullPath: '/ikea'
      preLoaderRoute: typeof IkeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/solicitud/$token': {
      id: '/solicitud/$token'
      path: '/solicitud/$token'
      fullPath: '/solicitud/$token'
      preLoaderRoute: typeof SolicitudTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IkeaRoute: IkeaRoute,
  PreciosRoute: PreciosRoute,
  ReservarRoute: ReservarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiciosRoute: ServiciosRoute,
  SolicitudTokenRoute: SolicitudTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
